# Generated by Django 6.0.2 on 2026-02-11 00:17

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('itemId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('qrCode', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('isCollection', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Borrow',
            fields=[
                ('borrowId', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('expectedReturn', models.DateField()),
                ('isReturned', models.BooleanField(default=False)),
                ('itemId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory_api.item')),
            ],
        ),
    ]
