# Generated by Django 6.0.2 on 2026-02-16 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='borrow',
            old_name='itemId',
            new_name='item',
        ),
        migrations.RemoveField(
            model_name='borrow',
            name='borrowId',
        ),
        migrations.RemoveField(
            model_name='item',
            name='itemId',
        ),
        migrations.AddField(
            model_name='borrow',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='item',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='borrow',
            name='email',
            field=models.EmailField(max_length=255),
        ),
    ]
